GET http://localhost:7071/api/HttpExample

###


POST http://localhost:7071/api/NewProduct
Content-Type: application/json

"hello world"

###

POST http://localhost:7071/api/NewProduct
Content-Type: application/json

{
    "name": "New Product",
    "description": "Description of New Product",
    "price": 9.99
}
